# Generated by Django 6.0.1 on 2026-02-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_auctionlist_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='comment_text',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='publisher',
            new_name='commenter',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='amount',
        ),
        migrations.AddField(
            model_name='bid',
            name='bid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
