# Generated by Django 6.0.1 on 2026-08-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_content_comment_comment_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlist',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
